window.onload = () => {

  @@include('./assets/utils.js')
  @@include('./assets/api.js')

  @@include('../components/_ui/popup/popup.js')
  @@include('../components/_ui/button/button.js')
  @@include('../components/_ui/dropdown/dropdown.js')
  @@include('../components/_ui/tabs/tabs.js')
  @@include('../components/_ui/input/input.js')
  @@include('../components/_ui/checkbox/checkbox.js')
  @@include('../components/_ui/checkboxselect/checkboxselect.js')
  @@include('../components/_ui/filters/filters.js')
  @@include('../components/_ui/tutorcard/tutorcard.js')
  @@include('../components/_ui/accordion/accordion.js')
  @@include('../components/_ui/application/application.js')
  @@include('../components/_ui/balance/balance.js')
  
  @@include('../components/banner/banner.js')
  @@include('../components/cookies/cookies.js')
  @@include('../components/header/header.js')
  @@include('../components/popular/popular.js')
  @@include('../components/reviews/reviews.js')
  @@include('../components/auth/auth.js')
  @@include('../components/catalog/catalog.js')
  @@include('../components/tutor/tutor.js')
  @@include('../components/profile-head/profile-head.js')
  @@include('../components/profile-about/profile-about.js')
  @@include('../components/profile-reviews/profile-reviews.js')
  @@include('../components/profile-schedule/profile-schedule.js')
  @@include('../components/chat/chat.js')
  @@include('../components/personal/personal.js')
  @@include('../components/joined/joined.js')

}