@@include('../../node_modules/swiper/swiper-bundle.js')
@@include('../../node_modules/@yaireo/fakescroll/fakescroll.js')
@@include('../../node_modules/inputmask/dist/inputmask.js')
@@include('../../node_modules/nouislider/dist/nouislider.js')
@@include('../../node_modules/smoothscroll-polyfill/dist/smoothscroll.js')
@@include('../../node_modules/decliner/dist/decliner.js')